# base image
FROM quay.io/fedora/python-312:312

# install biocode
RUN pip3 install biopython==1.81
RUN pip3 install biocode
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install biopython-convert

